"""Generate codebase_snapshot.md — a single structured Markdown file bundling the
main source files, for pasting into a web chat as context.

Usage:
    python make_snapshot.py

Edit FILES below to change what gets included. Output: codebase_snapshot.md
(gitignored by default; it is a regenerable artifact).
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "codebase_snapshot.md"

# Ordered list of source files to bundle (pipeline order, then helpers, then UI).
FILES: list[str] = [
    # Core pipeline
    "phase0_groq_translator.py",
    "phase1_eda_engine.py",
    "phase2_genetic_placer.py",
    "phase3_router.py",
    "phase4_analytics.py",
    "phase7_rl_placer.py",
    "phase8_multilayer_router.py",
    "phase9_export.py",
    "phase10_rag_copilot.py",
    "phase11_explorer.py",
    # Web app
    "app.py",
    # Shared helpers / entrypoints
    "component_library.py",
    "ingest_knowledge.py",
    "train_phase7_rl.py",
    "benchmark_placement.py",
    "benchmark_routing.py",
    # Frontend
    "frontend/index.html",
]

# Map file extension -> Markdown fenced-code language tag.
LANG = {
    ".py": "python",
    ".html": "html",
    ".css": "css",
    ".js": "javascript",
    ".json": "json",
    ".yml": "yaml",
    ".yaml": "yaml",
    ".md": "markdown",
}


def _lang(path: Path) -> str:
    return LANG.get(path.suffix.lower(), "")


def _anchor(rel: str) -> str:
    """GitHub-style anchor for a file path heading."""
    return rel.lower().replace("/", "").replace(".", "").replace("_", "-")


def build() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    present = [(rel, ROOT / rel) for rel in FILES if (ROOT / rel).is_file()]
    missing = [rel for rel in FILES if not (ROOT / rel).is_file()]

    total_lines = sum(
        len(p.read_text(encoding="utf-8", errors="replace").splitlines())
        for _, p in present
    )

    out: list[str] = []
    out.append("# Codebase Snapshot — AI-Accelerated EDA Engine")
    out.append("")
    out.append(
        f"> Auto-generated by `make_snapshot.py` on {stamp}. "
        f"{len(present)} files, {total_lines:,} lines of source. "
        "Paste into a web chat for full-codebase context. "
        "Pair with `project_context.md` (architecture/status) and `CLAUDE.md` (conventions)."
    )
    out.append("")
    if missing:
        out.append(f"> **Note:** {len(missing)} listed file(s) not found and skipped: "
                   + ", ".join(f"`{m}`" for m in missing))
        out.append("")

    # Table of contents
    out.append("## Contents")
    out.append("")
    for rel, p in present:
        n = len(p.read_text(encoding="utf-8", errors="replace").splitlines())
        out.append(f"- [`{rel}`](#{_anchor(rel)}) — {n} lines")
    out.append("")
    out.append("---")
    out.append("")

    # Each file
    for rel, p in present:
        text = p.read_text(encoding="utf-8", errors="replace")
        n = len(text.splitlines())
        out.append(f"## `{rel}`")
        out.append("")
        out.append(f"*{n} lines*")
        out.append("")
        out.append(f"```{_lang(p)}")
        out.append(text.rstrip("\n"))
        out.append("```")
        out.append("")
        out.append("---")
        out.append("")

    return "\n".join(out)


def main() -> None:
    content = build()
    OUTPUT.write_text(content, encoding="utf-8")
    lines = content.count("\n") + 1
    kb = len(content.encode("utf-8")) / 1024
    print(f"Wrote {OUTPUT.name}: {lines:,} lines, {kb:.0f} KB")


if __name__ == "__main__":
    main()
